Vagrant.configure('2') do |config|
  config.vm.box = 'packer_ubuntu'
  config.vm.network 'forwarded_port', guest: 22, host: 22022
  config.vm.network 'forwarded_port', guest: 80, host: 22080
  config.vm.network 'forwarded_port', guest: 443, host: 22443
  config.vm.network 'forwarded_port', guest: 3306, host: 22306
 
  config.vm.provision 'chef_solo' do |chef|
    chef.product = "chef-workstation"
    chef.arguments = '--chef-license accept'
    chef.add_recipe 'test'
    chef.nodes_path = 'nodes'
  end
end
